### ISSUE TITLE
Pan-STARRS filters aren't compatible with indices parameter

### ISSUE THREAD

**Issue by GurrenLagannTSS** [Askaniy/TrueColorTools#24]
For a "custom" index like _PAN-STARRS_PS1.g-CTIO_DECam.r_, TCT crashes citing an invalid color error or something. I presume it is because TCT assumes that the _-_ in _PAN-STARRS_ is an index linker, however it doesn't have data associated with the supposed _PAN_ filter.

A fix could be that TCT checks whether the first dash in an index is preceeding a dot, and treat said dash as part of the filter name in the index calculation if so.

**Comment by Askaniy** [comment]
Thanks! I'll fix it soon

**Comment by Askaniy** [comment]
Fixed in 827e96f33554dc3395cc8d4e39b1b6cf3981a6c2
